### ISSUE TITLE
"missing value where TRUE/FALSE needed" error

### ISSUE THREAD

**Issue by JosephMcCarter** [mskcc/facets#141]
I believe this may have been resolved in issue #2 however I'm getting the following error running FACETS 0.5.14

```
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
5: Setting LC_PAPER failed, using "C" 
6: Setting LC_MEASUREMENT failed, using "C" 
Error in while (dif > eps && iter < maxiter) { : 
  missing value where TRUE/FALSE needed
Calls: emcncf
Execution halted

```

**Comment by mflevine** [comment]
This issue seems to rise depending on the random seed. For some samples the pipeline will not successfully complete with all random seeds. I used this code to find which seeds will work for the failing samples.

```
for (i in 1:100){try({set.seed(i);print(i);xx <- preProcSample(rcmat, ndepth=50, ndepthmax=1500, unmatched=opt$unmatched);oo <- procSample(xx,cval=150);fit <- emcncf(oo);print("SUCCESS")}, silent=TRUE)}
```

**Comment by veseshan** [comment]
This is a locale issue and random number seed does not have anything to do with it. If the locale is set properly you can see it with the command Sys.getlocale(). For US-English it will be en_US.UTF-8. It is using the generic C because it is not set properly in your machine.

**Comment by mflevine** [comment]
I have resolved the locale issue:
```
> Sys.getlocale()
[1] "LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_US.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=C"
```
However, I still get the original error:
```
Error in while (dif > eps && iter < maxiter) { : 
  missing value where TRUE/FALSE needed
Calls: emcncf
```

**Comment by veseshan** [comment]
This may be a bug in emcncf. Does the naive fit show almost no change in the sample?

**Comment by veseshan** [comment]
This is triggered by samples with no change from diploid. emcncf has been modified to catch it. This should resolve the issue without having to resort to fishing for random number seed that works.

**Comment by rptashkin** [comment]
I still encountered this issue with modified emcncf
![emcncf_error_example](https://user-images.githubusercontent.com/12957101/75809209-6453b700-5d56-11ea-8792-2415c203e4e2.png)
. was able to resolve by lowering the cval from 150 to 50

**Comment by kibala93** [comment]
Hi, I am encountering this issue as well and I'm currently using facets v0.6.1. I only get the error with some seed values. 

"Error in while (dif > eps && iter < maxiter) { : 
  missing value where TRUE/FALSE needed"
